server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/url_shortener}
    username: ${SPRING_DATASOURCE_USERNAME:vidhanshu}
    password: ${SPRING_DATASOURCE_PASSWORD:Vidhanshu@7218}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1 hour in milliseconds